load("//rules:binaural.bzl", "binaural_clip_stems")

PITCH = 300
DURATION = 60

binaural_clip_stems(
    name = "alpha",
    pitch = PITCH,
    binaural_pitch = 10,
    duration = DURATION,
)

binaural_clip_stems(
    name = "beta",
    pitch = PITCH,
    binaural_pitch = 20,
    duration = DURATION
)
