# Configure linter
load("@com_github_bazelbuild_buildtools//buildifier:def.bzl", "buildifier")

buildifier(
    name = "buildifier-lint-fix",
    lint_mode = "fix",
)

buildifier(
    name = "buildifier-lint-warn",
    lint_mode = "warn",
)
